-- ============================================================================
-- IEPE Platform Master Database Schema
-- Supabase PostgreSQL Setup Script
-- ============================================================================

-- 1. BOOK SOURCES
CREATE TABLE IF NOT EXISTS public.book_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. QUESTIONS MASTER TABLE
CREATE TABLE IF NOT EXISTS public.questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id TEXT NOT NULL UNIQUE,
    book_source TEXT NOT NULL,
    chapter_name TEXT NOT NULL,
    question_number_in_book INT,
    question_text TEXT NOT NULL,
    options JSONB NOT NULL,
    correct_option TEXT NOT NULL,
    solution_text TEXT,
    exam_metadata TEXT,
    admin_tags TEXT[],
    difficulty TEXT CHECK (difficulty IN ('Easy', 'Easy-Moderate', 'Moderate', 'Moderate-Hard', 'Hard')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. MOCK TESTS
CREATE TABLE IF NOT EXISTS public.tests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    total_time_minutes INT NOT NULL,
    marks_per_correct NUMERIC DEFAULT 1,
    negative_marks_per_incorrect NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'scheduled', 'live', 'completed', 'archived')),
    result_policy TEXT DEFAULT 'instant' CHECK (result_policy IN ('instant', 'scheduled')),
    result_release_at TIMESTAMPTZ,
    start_time TIMESTAMPTZ,
    end_time TIMESTAMPTZ,
    total_questions INT DEFAULT 0,
    allow_pausing BOOLEAN DEFAULT FALSE,
    show_in_question_timer BOOLEAN DEFAULT FALSE,
    is_dynamically_shuffled BOOLEAN DEFAULT FALSE,
    is_proctored BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TEST QUESTIONS (JUNCTION TABLE)
CREATE TABLE IF NOT EXISTS public.test_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id BIGINT REFERENCES public.tests(id) ON DELETE CASCADE,
    question_id BIGINT REFERENCES public.questions(id) ON DELETE CASCADE,
    question_override_data JSONB,
    test_name TEXT,
    test_status TEXT,
    total_time_minutes INT,
    marks_per_correct REAL,
    penalty_per_incorrect REAL
);

-- 5. TEST RESULTS
CREATE TABLE IF NOT EXISTS public.test_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    mock_test_id BIGINT REFERENCES public.tests(id) ON DELETE SET NULL,
    test_type TEXT NOT NULL DEFAULT 'practice',
    session_type TEXT NOT NULL DEFAULT 'practice',
    test_mode TEXT DEFAULT 'practice' CHECK (test_mode IN ('practice', 'timed')),
    time_limit_minutes INT,
    score NUMERIC,
    score_percentage NUMERIC,
    accuracy NUMERIC,
    total_questions INT,
    total_correct INT,
    total_incorrect INT,
    total_skipped INT,
    total_time_taken INT,
    srs_feedback_log JSONB DEFAULT '{}'::jsonb,
    submitted_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. ANSWER LOG
CREATE TABLE IF NOT EXISTS public.answer_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result_id BIGINT NOT NULL REFERENCES public.test_results(id) ON DELETE CASCADE,
    question_id BIGINT NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    user_answer TEXT,
    status TEXT NOT NULL CHECK (status IN ('correct', 'incorrect', 'skipped')),
    time_taken INT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. BOOKMARKED QUESTIONS (SRS)
CREATE TABLE IF NOT EXISTS public.bookmarked_questions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    question_id TEXT NOT NULL REFERENCES public.questions(question_id) ON DELETE CASCADE,
    personal_note TEXT,
    custom_tags TEXT[],
    user_difficulty_rating SMALLINT,
    srs_repetitions INT DEFAULT 0,
    srs_ease_factor NUMERIC DEFAULT 2.5,
    srs_interval INT DEFAULT 0,
    next_review_date DATE,
    is_custom_reminder_active BOOLEAN DEFAULT FALSE,
    custom_next_review_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. REVIEW HISTORY (SRS)
CREATE TABLE IF NOT EXISTS public.review_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    bookmark_id UUID NOT NULL REFERENCES public.bookmarked_questions(id) ON DELETE CASCADE,
    question_id TEXT NOT NULL,
    performance_rating INT NOT NULL CHECK (performance_rating >= 1 AND performance_rating <= 4),
    interval_at_review INT,
    ease_factor_at_review NUMERIC,
    repetitions_at_review INT,
    new_interval INT,
    new_ease_factor NUMERIC,
    new_repetitions INT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. DAILY REVIEW SUMMARY
CREATE TABLE IF NOT EXISTS public.daily_review_summary (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    reviews_completed INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. ERROR REPORTS
CREATE TABLE IF NOT EXISTS public.error_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
    reported_by_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    report_description TEXT,
    report_tag TEXT,
    status TEXT DEFAULT 'new' CHECK (status IN ('new', 'reviewed', 'resolved', 'dismissed')),
    admin_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. PRACTICE PLANS
CREATE TABLE IF NOT EXISTS public.practice_plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    plan_type TEXT NOT NULL,
    content JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 12. SAVED PRACTICE SESSIONS
CREATE TABLE IF NOT EXISTS public.saved_practice_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    session_name TEXT NOT NULL,
    session_state JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 13. USER NOTIFICATION PREFERENCES
CREATE TABLE IF NOT EXISTS public.user_notification_preferences (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    enable_email_reminders BOOLEAN DEFAULT TRUE,
    enable_in_app_reminders BOOLEAN DEFAULT TRUE,
    reminder_time VARCHAR DEFAULT '09:00',
    user_timezone VARCHAR DEFAULT 'Asia/Kolkata',
    srs_pacing_mode NUMERIC DEFAULT 0.00,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 14. STUDENT NOTIFICATIONS
CREATE TABLE IF NOT EXISTS public.student_notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    link VARCHAR,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
